services:
  webchatroom:
    build:
      context: ./WebChatRoom
      dockerfile: Dockerfile
    container_name: webchatroom
    restart: always
    networks:
      - appnet
    environment:
      - ASPNETCORE_URLS=http://+:80


networks:
  appnet:
    external: true