services:
  web-chat-room:
    image: ghcr.io/radendk/chatroom:latest
    container_name: web-chat-room
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - homeserver_web
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  homeserver_web:
    external: true
